# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
    - quay-data:/var/lib/elasticsearch

redis:
  image: "redis:alpine"
  ports:
    - "6379:6379"
  volumes:
    - redis-data:/data
